In [18]:
# https://www.pytry3g.com/entry/2018/04/27/225711

from sklearn import datasets
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split

iris = datasets.load_iris()
data = iris.data
target = iris.target
train_x, test_x, train_t, test_t = train_test_split(data, target, test_size = 0.1)

In [25]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as O

class NN(nn.Module):
    def __init__(self):
        super(NN, self).__init__()
        self.layer = nn.Linear(4,3)
        
    def forward(self, x):
        return self.layer(x)

model = NN()
optimizer = O.Adam(model.parameters(), lr=0.1)
criterion = nn.CrossEntropyLoss()

In [40]:
for _ in range(40):
    train_x , train_t = shuffle(train_x, train_t)
    for i in range(0, len(train_x), 30):
        x=torch.tensor(train_x[i:i+30], dtype=torch.float)
        t=torch.tensor(train_t[i:i+30], dtype=torch.long)
        optimizer.zero_grad()
        y = model(x)
        loss = criterion(y, t)
        print(loss)
        loss.backward()
        optimizer.step()

tensor(0.0868, grad_fn=<NllLossBackward>)
tensor(0.1261, grad_fn=<NllLossBackward>)
tensor(0.1385, grad_fn=<NllLossBackward>)
tensor(0.1392, grad_fn=<NllLossBackward>)
tensor(0.1768, grad_fn=<NllLossBackward>)
tensor(0.1173, grad_fn=<NllLossBackward>)
tensor(0.1564, grad_fn=<NllLossBackward>)
tensor(0.1854, grad_fn=<NllLossBackward>)
tensor(0.1043, grad_fn=<NllLossBackward>)
tensor(0.0838, grad_fn=<NllLossBackward>)
tensor(0.0786, grad_fn=<NllLossBackward>)
tensor(0.1219, grad_fn=<NllLossBackward>)
tensor(0.1302, grad_fn=<NllLossBackward>)
tensor(0.1693, grad_fn=<NllLossBackward>)
tensor(0.1620, grad_fn=<NllLossBackward>)
tensor(0.1150, grad_fn=<NllLossBackward>)
tensor(0.1280, grad_fn=<NllLossBackward>)
tensor(0.1122, grad_fn=<NllLossBackward>)
tensor(0.1014, grad_fn=<NllLossBackward>)
tensor(0.2436, grad_fn=<NllLossBackward>)
tensor(0.0983, grad_fn=<NllLossBackward>)
tensor(0.1285, grad_fn=<NllLossBackward>)
tensor(0.1246, grad_fn=<NllLossBackward>)
tensor(0.1344, grad_fn=<NllLossBac

In [27]:
tensor = torch.tensor(test_x, dtype=torch.float, requires_grad=False)
result = model(tensor)
#   モデルがテストデータを予測した結果
predicted = torch.max(result, 1)[1]
# 正解データ
label = torch.tensor(test_t, dtype=torch.long)
print("Accuracy: {}".format((predicted == label).sum().item() / len(label)))

Accuracy: 1.0


In [28]:
tensor = torch.tensor([1,2,3])
print(tensor.sum())
# tensor(6)
print(tensor.sum().item())

tensor(6)
6


In [29]:
predicted

tensor([0, 0, 2, 2, 0, 1, 0, 1, 1, 1, 0, 0, 2, 1, 2])

In [38]:
torch.max(result,1)

(tensor([7.9987, 9.8020, 3.6776, 4.5567, 9.0946, 2.7622, 9.8798, 3.0515, 3.0394,
         2.8896, 9.7733, 9.8841, 5.1822, 2.9902, 4.8745],
        grad_fn=<MaxBackward0>),
 tensor([0, 0, 2, 2, 0, 1, 0, 1, 1, 1, 0, 0, 2, 1, 2]))

In [39]:
loss

tensor(0.1694, grad_fn=<NllLossBackward>)