In [3]:
# https://qiita.com/kenmikamin/items/b9a50ed0b48584453b99　の前半部 と
# https://qiita.com/perrying/items/857df46bb6cdc3047bd8　
import torch
x = torch.rand(5,3)
x

tensor([[0.9710, 0.9718, 0.7808],
        [0.8483, 0.6924, 0.4905],
        [0.1161, 0.8003, 0.2916],
        [0.7086, 0.1636, 0.3710],
        [0.3153, 0.7842, 0.9109]])

In [4]:
x.size()

torch.Size([5, 3])

In [5]:
y = torch.rand(5,3)
x + y

tensor([[1.0197, 1.8996, 1.1677],
        [1.5743, 1.6831, 0.7330],
        [0.3190, 1.5549, 1.2238],
        [0.9900, 0.5320, 0.5533],
        [1.2624, 0.9188, 1.0919]])

In [6]:
print(x + y)

tensor([[1.0197, 1.8996, 1.1677],
        [1.5743, 1.6831, 0.7330],
        [0.3190, 1.5549, 1.2238],
        [0.9900, 0.5320, 0.5533],
        [1.2624, 0.9188, 1.0919]])


In [7]:
result = torch.Tensor(5,3)
torch.add(x, y, out=result)
result

tensor([[1.0197, 1.8996, 1.1677],
        [1.5743, 1.6831, 0.7330],
        [0.3190, 1.5549, 1.2238],
        [0.9900, 0.5320, 0.5533],
        [1.2624, 0.9188, 1.0919]])

In [8]:
y.add_(x)
y

tensor([[1.0197, 1.8996, 1.1677],
        [1.5743, 1.6831, 0.7330],
        [0.3190, 1.5549, 1.2238],
        [0.9900, 0.5320, 0.5533],
        [1.2624, 0.9188, 1.0919]])

In [9]:
x[:, 1]

tensor([0.9718, 0.6924, 0.8003, 0.1636, 0.7842])

In [10]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [11]:
b = a.numpy()
b

array([ 1.,  1.,  1.,  1.,  1.], dtype=float32)

In [12]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[ 2.  2.  2.  2.  2.]


In [13]:
import numpy as np 
a=np.ones(5)
b=torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [14]:
import torch.nn as nn 
import torch.optim as optim

In [15]:
model = nn.Sequential()
model.add_module('fc1', nn.Linear(10,100))
model.add_module('relu', nn.ReLU())
model.add_module('fc2', nn.Linear(100,10))

In [16]:
layer = []
layer.append(nn.Linear(10,100))
layer.append(nn.ReLU())
layer.append(nn.Linear(100,10))
model=nn.Sequential(*layer)

In [17]:
import torch.nn.functional as F
import torch.optim as optim
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.fc1 = nn.Linear(10,100)
        self.fc2 = nn.Linear(100,10)
    
    def forward(self, x):
        x = self.fc1(x)
        x = F.relu(x)
        x = self.fc2(x)
        return x

In [18]:
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        layer = [nn.Linear(10,10) for _ in range(10)]
        self.layer = nn.ModuleList(layer)
        
    def forward(self, x):
        for i in range(len(self.layer)):
            x = self.layer[i](x)
        return x
    
model=Model()
optimize = optim.SGD(model.parameters(), lr=0.1)


In [21]:
import torchvision.models as models
model = models.resnet18()
model = model.to('cpu')
optimizer = optim.SGD(model.parameters(), lr=0.1, momentum=0.9)
criterion=nn.MSELoss()
inputs = torch.randn(1,3,224,224)
target = torch.randn(1,1000)
target.requires_grad=False

model.train()
for i in range(100):
    out=model(inputs)
    loss=criterion(out, target)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    

In [29]:
class RNN(nn.Module):
    def __init__(self, data_size, hidden_size, output_size):
        super(RNN, self).__init__()
        self.hidden_size=hidden_size
        input_size=data_size + hidden_size
        self.i2h = nn.Linear(input_size, hidden_size)
        self.h2o = nn.Linear(hidden_size, output_size)
        
    def forward(self, data, last_hidden):
        inputs = torch.cat((data, last_hidden), 1)
        hidden = self.i2h(inputs)
        output = self.h2o(hidden)
        return hidden, output
    


In [32]:
RNN = RNN()
# optimizerなど省略
for i in range(10):
    hidden, output = RNN(inputs, hidden)
    loss += criterion(output, target)
loss.backward()
optimizer.step()

TypeError: __init__() missing 3 required positional arguments: 'data_size', 'hidden_size', and 'output_size'